In [7]:
from feature_manager import FeatureManager
from PIL import Image
import numpy as np
from os import walk, path
from matplotlib.colors import rgb_to_hsv
from pprint import pprint

def load_image(fn):
    img = Image.open(fn)
    img.load()
    data = np.asarray(img, dtype="int32")
    return data

In [8]:
# wk = tuple(walk("./feature-engineering-test-files"))[0]

# for fn in wk[2]:
#     if '-m.jpg' in fn:
#         mask_im = load_image(fn)
#         im = load_image(fn.replace("-m.jpg", ".jpg"))
#         features = {"color_features": ["HistogramHSV"]}
#         # features = None
#         # features = {"geometric_features": ["Area", "Perimeter"]}
#         fm = FeatureManager(image=im, mask_image=mask_im, feature_dict=features)
#         pprint(fm())

wk = tuple(walk("../../test_images/"))[1:3]

defective = 0
total = 0

for folder in wk:
    a = folder[0].split(path.sep)
    a.insert(3, "test-mask")
    test_prefix = "/".join(a)
    for image in folder[2]:
        split_name = image.split(".")
        split_name.insert(1, "-m.")
        mask_name = "".join(split_name)
        mask_path_str=test_prefix+path.sep+mask_name
        image_path_str=folder[0]+path.sep+image

        if path.isfile(mask_path_str):
            total += 1
            fm = FeatureManager(image=load_image(image_path_str), mask_image=load_image(mask_path_str), feature_dict=None)
            try:
                output = fm()
            except:
                print(mask_path_str, image_path_str)
                defective += 1
            pprint(output)
    
    print(defective, total)

{'color_features': {'HistogramHSV': (array([ 81, 252, 372, 317, 303, 391, 324, 188, 173,  99]),
                                     array([ 23. ,  46.8,  70.6,  94.4, 118.2, 142. , 165.8, 189.6, 213.4,
       237.2, 261. ])),
                    'MeanHSV': [0.8656691505679475,
                                0.47413339337219407,
                                142.1168367346939]},
 'geometric_features': {'Area': 540,
                        'AreaPerimeter': 3.75,
                        'InsideRadialContact': (array([134, 113,  57,  50,  64,  35,  36,  24,  16,  11]),
                                                array([ 1.       ,  1.977    ,  2.954    ,  3.9310002,  4.908    ,
        5.885    ,  6.8620005,  7.839    ,  8.816    ,  9.793    ,
       10.77     ], dtype=float32)),
                        'Perimeter': 144}}
{'color_features': {'HistogramHSV': (array([ 22,  96, 201, 188, 156, 355, 385, 326, 385, 386]),
                                     array([ 27. ,  50.4,  73.8,  